import {useEffect, useState} from "react"
import {Button, Card, Flex, Stack, Text, TextInput} from "@sanity/ui"
import {useClient} from "sanity"
import {apiVersion} from "../../env"
import {Choice, Field, MediaFields, MovementEditor, NewComposerForm, SaleForm, SharedRecordingDetails} from "./components"
import {createComposer, createRecording, createRecordingProduct, createWork, createWorkProduct, listComposers, listWorks, updateWorkMovements} from "./services/music"
import type {Composer, ComposerDraft, CreatedMusic, Movement, RecordingDraft, SaleDraft, Work, WorkDraft} from "./types"

type Step = "question" | "works" | "composers" | "new-work" | "existing-work" | "upload" | "sale-question" | "sale" | "complete"
type Props = {onComplete: (music: CreatedMusic) => void; onCancel: () => void}
type SaleMap = Record<string, SaleDraft>
const emptyMedia = (): RecordingDraft => ({title: "", artist: "Katie Lansdale", mediaType: "audio"})

export default function AddRecordingWorkflow({onComplete, onCancel}: Props) {
  const client = useClient({apiVersion})
  const [step, setStep] = useState<Step>("question")
  const [work, setWork] = useState<Work | null>(null)
  const [isExisting, setIsExisting] = useState(false)
  const [composer, setComposer] = useState<Composer | null>(null)
  const [movements, setMovements] = useState<Movement[]>([])
  const [workDraft, setWorkDraft] = useState<Omit<WorkDraft, "composerId" | "movements">>({title: ""})
  const [works, setWorks] = useState<Work[]>([])
  const [composers, setComposers] = useState<Composer[]>([])
  const [term, setTerm] = useState("")
  const [addingComposer, setAddingComposer] = useState(false)
  const [uploadMode, setUploadMode] = useState<"individual" | "whole">("individual")
  const [media, setMedia] = useState<RecordingDraft[]>([])
  const [artist, setArtist] = useState("Katie Lansdale")
  const [yearReleased, setYearReleased] = useState<number | undefined>()
  const [coverArt, setCoverArt] = useState<unknown>()
  const [createdMusic, setCreatedMusic] = useState<CreatedMusic | null>(null)
  const [saleDrafts, setSaleDrafts] = useState<SaleMap>({})
  const [selectedSales, setSelectedSales] = useState<string[]>([])
  const [saving, setSaving] = useState(false)
  const [uploadStates, setUploadStates] = useState<Record<number, boolean>>({})
  const [error, setError] = useState<string | null>(null)
  const uploadBusy = Object.values(uploadStates).some(Boolean)
  useEffect(() => { if (step === "works") void listWorks(client).then(setWorks).catch(() => setError("The music catalog could not be loaded. Please try again.")); if (step === "composers") void listComposers(client).then(setComposers).catch(() => setError("The composer catalog could not be loaded. Please try again.")) }, [client, step])
  const filter = term.trim().toLocaleLowerCase()
  const filteredWorks = works.filter((item) => !filter || [item.title, item.catalogNumber, item.composer?.name].filter(Boolean).some((value) => value!.toLocaleLowerCase().includes(filter)))
  const filteredComposers = composers.filter((item) => !filter || [item.name, item.sortName].filter(Boolean).some((value) => value!.toLocaleLowerCase().includes(filter)))
  const uploadTargets = (sourceMovements = movements, sourceWork = work) => sourceMovements.length > 1 && uploadMode === "individual" ? sourceMovements.map((movement) => ({title: movement.title || `Movement ${movement.number}`, movementNumber: movement.number})) : [{title: sourceMovements.length === 1 && sourceMovements[0].title ? sourceMovements[0].title : sourceWork?.title ?? workDraft.title, movementNumber: undefined}]
  const createUploadDrafts = (sourceMovements = movements, sourceWork = work) => uploadTargets(sourceMovements, sourceWork).map((target) => ({...emptyMedia(), title: target.title, movementNumber: target.movementNumber}))
  const setMode = (mode: "individual" | "whole") => { setUploadMode(mode); const targets = movements.length > 1 && mode === "individual" ? movements.map((movement) => ({title: movement.title || `Movement ${movement.number}`, movementNumber: movement.number})) : [{title: movements.length === 1 && movements[0].title ? movements[0].title : work?.title ?? workDraft.title, movementNumber: undefined}]; setMedia(targets.map((target, index) => ({...emptyMedia(), ...media[index], title: target.title, movementNumber: target.movementNumber}))) }
  const uploadCoverArt = async (file: File) => { try { const asset = await client.assets.upload("image", file); setCoverArt({_type: "image", asset: {_type: "reference", _ref: asset._id}}) } catch { setError("The artwork could not be uploaded. Please try again.") } }
  const saveComposer = async (draft: ComposerDraft) => { const created = await createComposer(client, draft); setComposer(created); setMovements([{number: 1, title: ""}]); setAddingComposer(false); setStep("new-work") }
  const saveNewWork = async () => { if (!composer || !workDraft.title.trim()) return; setSaving(true); try { const savedMovements = movements.filter((movement) => movement.title.trim()); const created = await createWork(client, {...workDraft, title: workDraft.title.trim(), composerId: composer._id, movements: savedMovements}); const newWork = {_id: created._id, title: created.title, movements: savedMovements}; setMovements(savedMovements); setWork(newWork); setIsExisting(false); setMedia(createUploadDrafts(savedMovements, newWork)); setStep("upload") } catch { setError("The work could not be saved. Please try again.") } finally { setSaving(false) } }
  const continueExisting = () => { if (!work) return; setMedia(createUploadDrafts()); setStep("upload") }
  const saveRecordings = async () => { if (!work || !artist.trim() || !media.length) return; setSaving(true); try { const updatedWork = await updateWorkMovements(client, work._id, movements); const recordings = await Promise.all(media.map((item) => createRecording(client, updatedWork._id, {...item, artist, yearReleased, coverArt}))); setCreatedMusic({workId: updatedWork._id, recordingIds: recordings.map((recording) => recording._id)}); setStep("sale-question") } catch { setError("The recordings could not be saved. Please try again.") } finally { setSaving(false) } }
  const saleTargets = createdMusic ? [{key: "work", label: `Entire work: ${work?.title}`, ids: createdMusic.recordingIds, kind: "work" as const}, ...(movements.length > 1 && uploadMode === "individual" ? media.map((item, index) => ({key: `movement-${index}`, label: item.title, ids: [createdMusic.recordingIds[index]], kind: "recording" as const})) : [])] : []
  const beginSale = () => { const defaults: SaleMap = {}; saleTargets.forEach((target) => { defaults[target.key] = {title: `${target.label.replace("Entire work: ", "")} — ${artist}${yearReleased ? ` (${yearReleased})` : ""}`, price: 0, deliveryTypes: ["digitalDownload"]} }); setSaleDrafts(defaults); setStep("sale") }
  const saveSales = async () => { if (!createdMusic) return; setSaving(true); try { await Promise.all(selectedSales.map(async (key) => { const target = saleTargets.find((item) => item.key === key); const draft = saleDrafts[key]; if (!target || !draft?.title) return; if (target.kind === "work") await createWorkProduct(client, draft, createdMusic.workId, target.ids); else await createRecordingProduct(client, draft, target.ids) })); setStep("complete") } catch { setError("One or more sale listings could not be saved. Please try again.") } finally { setSaving(false) } }
  const back = () => { if (step === "question") return onCancel(); const previous: Partial<Record<Step, Step>> = {works: "question", composers: "question", "new-work": "composers", "existing-work": "works", upload: isExisting ? "existing-work" : "new-work", "sale-question": "upload", sale: "sale-question", complete: "sale-question"}; setStep(previous[step] ?? "question") }
  return <Card padding={5} radius={2} shadow={1}><Stack space={5}><Flex justify="space-between" align="center"><Text size={3} weight="semibold">{step === "sale" ? "List for sale" : "Add a recording"}</Text><Flex gap={2}><Button text="Back" mode="bleed" disabled={uploadBusy} onClick={back} /><Button text="Cancel" mode="bleed" disabled={uploadBusy} onClick={onCancel} /></Flex></Flex>{error && <Card padding={3} tone="critical"><Text>{error}</Text></Card>}
    {step === "question" && <Stack space={4}><Text size={2} weight="semibold">What would you like to add?</Text><Choice title="New work" description="Add a new work and its first recording." onClick={() => {setTerm(""); setStep("composers")}} /><Choice title="New recording of an existing work" description="Choose a work already in your uploads." onClick={() => {setTerm(""); setStep("works")}} /></Stack>}
    {step === "works" && <Stack space={3}><Text>Choose a work from your website. Use the filter if you know the composer or work name.</Text><TextInput placeholder="Filter by composer or work name" value={term} onChange={(event) => setTerm(event.currentTarget.value)} />{filteredWorks.map((item, index) => <Stack key={item._id} space={2}>{(index === 0 || filteredWorks[index - 1].composer?._id !== item.composer?._id) && <Text size={2} weight="semibold">{item.composer?.name ?? "Unknown composer"}</Text>}<Choice title={item.title} description={(item.movements ?? []).map((movement) => `${movement.number}. ${movement.title}`).join(" — ") || "Single-movement work"} onClick={() => {setWork(item); setIsExisting(true); setMovements(item.movements ?? []); setStep("existing-work")}} /></Stack>)}</Stack>}
    {step === "composers" && <Stack space={3}>{addingComposer ? <NewComposerForm onSave={saveComposer} onBack={() => setAddingComposer(false)} /> : <><Text>Choose a composer, or add a new one.</Text><TextInput placeholder="Filter by composer name" value={term} onChange={(event) => setTerm(event.currentTarget.value)} />{filteredComposers.map((item) => <Choice key={item._id} title={item.name} onClick={() => {setComposer(item); setMovements([{number: 1, title: ""}]); setStep("new-work")}} />)}<Button text="+ Add a new composer" mode="ghost" onClick={() => setAddingComposer(true)} /></>}</Stack>}
    {step === "new-work" && <Stack space={4}><Text size={2} weight="semibold">Create a new work by {composer?.name}</Text><Field label="Work title" required placeholder="Sonata no. 2 in A minor" value={workDraft.title} onChange={(title) => setWorkDraft({...workDraft, title})} /><Field label="Subtitle" value={workDraft.subtitle} onChange={(subtitle) => setWorkDraft({...workDraft, subtitle})} /><Text size={2} weight="semibold">Movements (optional)</Text><MovementEditor movements={movements} firstPlaceholder="Grave" onChange={setMovements} /><Field label="Catalog number" placeholder="BWV 1003" value={workDraft.catalogNumber} onChange={(catalogNumber) => setWorkDraft({...workDraft, catalogNumber})} /><Field label="Arranged by" value={workDraft.arrangedBy} onChange={(arrangedBy) => setWorkDraft({...workDraft, arrangedBy})} /><Field label="Year composed" type="number" placeholder="1720" value={workDraft.yearComposed} onChange={(value) => setWorkDraft({...workDraft, yearComposed: value ? Number(value) : undefined})} /><Field label="Instrumentation" placeholder="Solo Violin" value={workDraft.instrumentation} onChange={(instrumentation) => setWorkDraft({...workDraft, instrumentation})} /><Button text="Continue to upload music" tone="primary" loading={saving} disabled={!workDraft.title.trim()} onClick={saveNewWork} /></Stack>}
    {step === "existing-work" && <Stack space={4}><Text size={2} weight="semibold">{work?.title}</Text><MovementEditor movements={movements} onChange={setMovements} /><Button text="Continue to upload music" tone="primary" onClick={continueExisting} /></Stack>}
    {step === "upload" && <Stack space={4}>{movements.length > 1 && <Flex gap={3}><Button text="Upload each movement separately" mode={uploadMode === "individual" ? "default" : "ghost"} disabled={uploadBusy} onClick={() => setMode("individual")} /><Button text="Upload all movements in one recording" mode={uploadMode === "whole" ? "default" : "ghost"} disabled={uploadBusy} onClick={() => setMode("whole")} /></Flex>}{media.map((item, index) => <Card key={`${item.title}-${index}`} padding={4} tone="transparent"><Stack space={3}><Text size={2} weight="semibold">{item.title}</Text><MediaFields draft={item} sanityToken={client.config().token} onBusyChange={(busy) => setUploadStates((current) => ({...current, [index]: busy}))} onChange={(next) => setMedia(media.map((current, currentIndex) => currentIndex === index ? next : current))} /></Stack></Card>)}{media.length > 0 && <SharedRecordingDetails artist={artist} yearReleased={yearReleased} coverArtSelected={Boolean(coverArt)} onArtistChange={setArtist} onYearChange={setYearReleased} onCoverArtSelected={uploadCoverArt} />}<Button text="Save recording" tone="primary" loading={saving} disabled={uploadBusy || !artist.trim() || !media.length} onClick={saveRecordings} /></Stack>}
    {step === "sale-question" && <Stack space={4}><Text>Would you like to make this music available for purchase?</Text><Choice title="Set up for sale" description="Create a customer-facing listing now." onClick={beginSale} /><Choice title="Save for later" description="Keep the recording in your library without a listing." onClick={() => setStep("complete")} /></Stack>}
    {step === "sale" && <Stack space={4}><Text>Select the recordings or entire work you would like to list.</Text>{saleTargets.map((target) => <Card key={target.key} padding={4} tone="transparent"><Stack space={3}><label><input type="checkbox" checked={selectedSales.includes(target.key)} onChange={() => setSelectedSales(selectedSales.includes(target.key) ? selectedSales.filter((item) => item !== target.key) : [...selectedSales, target.key])} /> List {target.label}</label>{selectedSales.includes(target.key) && <SaleForm draft={saleDrafts[target.key]} onChange={(draft) => setSaleDrafts({...saleDrafts, [target.key]: draft})} />}</Stack></Card>)}<Button text="Create selected sale listings" tone="primary" loading={saving} disabled={!selectedSales.length || selectedSales.some((key) => !saleDrafts[key]?.title || saleDrafts[key].price < 0)} onClick={saveSales} /></Stack>}
    {step === "complete" && <Stack space={4}><Text size={3} weight="semibold">Success — your music has been saved.</Text><Text>{selectedSales.length ? "Your selected sale listings have also been created." : "It is saved in your uploads and can be listed for sale later."}</Text><Button text="Return to Music Store" tone="primary" onClick={() => onComplete(createdMusic!)} /></Stack>}
  </Stack></Card>
}
